spring:
  application:
    name: user_service
  config:
    import: configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/authorFinderApp?createDatabaseIfNotExist=true
    username: root
    password: Root@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
